# Generated by Django 6.0.3 on 2026-05-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
