# Generated by Django 6.0.3 on 2026-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cooking', 'Cooking'), ('serving', 'Serving'), ('done', 'Done')], default='waiting', max_length=20),
        ),
    ]
