# Generated by Django 6.0.4 on 2026-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_missing_updated_at_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cooking', 'Cooking'), ('serving', 'Serving'), ('done', 'Done')], default='waiting', max_length=20),
        ),
    ]
